trigger:
- master

schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight (UTC) build
  branches:
    include:
    - master
  always: true

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    make ciprepare
  displayName: 'Install Rust Dependencies'
- script: |
    make --keep-going format check=true
  displayName: 'Check formatting'
- script: |
    make --keep-going test
  displayName: 'Run rust tests'
- script: |
    make --keep-going clippy
  displayName: 'Run clippy linter'
- script: |
    make --keep-going mainboards
  displayName: 'Build all mainboards'
- script: |
    ./scripts/generate-size-report.sh
  displayName: 'Generate report of binary sizes'
- script: |
    cd src/mainboard/sifive/hifive
    PAYLOAD_A=../../../../payloads/src/external/simple/testtesttest make
  displayName: 'Build SiFive board for RISC-V'
- script: |
    cd src/mainboard/emulation/qemu-riscv
    make
  displayName: 'Build QEMU virt board for RISC-V'
- script: |
    cd src/mainboard/emulation/qemu-q35
    make
  displayName: 'Build QEMU q35 board for x86'
- script: |
    set -e
    QVER=5.1.0
    curl -L https://github.com/qemu/qemu/archive/v$QVER.tar.gz|tar xz
    pushd qemu-$QVER
    mkdir build && cd build
    ../configure --target-list=riscv64-softmmu,x86_64-softmmu --audio-drv-list= --python=/usr/bin/python3 --disable-bzip2 --disable-curl --disable-curses --disable-docs --disable-gcrypt --disable-gnutls --disable-gtk --disable-guest-agent --disable-kvm --disable-libssh --disable-libusb --disable-libxml2 --disable-live-block-migration --disable-lzo --disable-mpath --disable-nettle --disable-numa --disable-opengl --disable-rdma --disable-replication --disable-sdl --disable-snappy --disable-spice --disable-tpm --disable-usb-redir --disable-vhost-crypto --disable-vhost-net --disable-vhost-scsi --disable-vhost-user --disable-vhost-vsock --disable-virglrenderer --disable-vnc --disable-vnc-jpeg --disable-vnc-png --disable-vnc-sasl --disable-xen --disable-debug-mutex --disable-debug-info --disable-debug-tcg --enable-virtfs
    make -j$(($(nproc) + 1)) qemu-img
    make -j$(($(nproc) + 1)) -C x86_64-softmmu qemu-system-x86_64
    make -j$(($(nproc) + 1)) -C riscv64-softmmu qemu-system-riscv64
    popd
    mkdir bin
    ln -s $(realpath qemu-$QVER/build/qemu-img) bin/
    ln -s $(realpath qemu-$QVER/build/x86_64-softmmu/qemu-system-x86_64) bin/
    ln -s $(realpath qemu-$QVER/build/riscv64-softmmu/qemu-system-riscv64) bin/
  displayName: 'Build QEMU for RISC-V and x86_64'
- script: |
    export PATH=$(realpath bin):$PATH
    cd src/mainboard/sifive/hifive
    PAYLOAD_A=../../../../payloads/src/external/simple/testtesttest timeout 120s make run | tee serial
    grep TESTTESTTEST serial
  displayName: 'RISC-V SiFive board QEMU Test'
- script: |
    export PATH=$(realpath bin):$PATH
    cd src/mainboard/emulation/qemu-riscv
    timeout 30s make run | tee serial
    grep "Running payload" serial
  displayName: 'RISC-V QEMU Virt board QEMU Test'
- script: |
    export PATH=$(realpath bin):$PATH
    cd src/mainboard/emulation/qemu-q35
    timeout 120s make run | tee serial
    grep "Running payload" serial
  displayName: 'x86 q35 board QEMU Test'
